import Head from 'next/head'
import React from 'react'

const about = () => {

  return (
    <>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h2>About Page</h2>
      </main>
    </>
  )
}

export default about